[CmdletBinding()]
param(
    [string]$ProfilesPath = (Join-Path $PSScriptRoot '..\profiles\weapon-profiles.json'),
    [string]$OutputPath = (Join-Path $PSScriptRoot '..\gamedata\configs\mod_system_zzzzzzzzzzzzzzzz_sep_frosty_ak101_integration.ltx'),
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$invariantCulture = [System.Globalization.CultureInfo]::InvariantCulture

function Get-RequiredVector {
    param(
        [Parameter(Mandatory)]$Object,
        [Parameter(Mandatory)][string]$Property,
        [Parameter(Mandatory)][string]$Context
    )

    $value = $Object.$Property
    if ($null -eq $value -or @($value).Count -ne 3) {
        throw "$Context.$Property must contain exactly three numbers."
    }

    $vector = @($value | ForEach-Object { [double]$_ })
    foreach ($component in $vector) {
        if ([double]::IsNaN($component) -or [double]::IsInfinity($component)) {
            throw "$Context.$Property contains a non-finite value."
        }
    }

    return $vector
}

function Get-OptionalVector {
    param(
        [Parameter(Mandatory)]$Object,
        [Parameter(Mandatory)][string]$Property,
        [Parameter(Mandatory)][string]$Context,
        [Parameter(Mandatory)][double[]]$Fallback
    )

    if ($Object.PSObject.Properties.Name -contains $Property) {
        return Get-RequiredVector $Object $Property $Context
    }

    return $Fallback
}

function Subtract-Vector {
    param(
        [Parameter(Mandatory)][double[]]$Left,
        [Parameter(Mandatory)][double[]]$Right
    )

    return @(
        $Left[0] - $Right[0]
        $Left[1] - $Right[1]
        $Left[2] - $Right[2]
    )
}

function Format-Number {
    param([Parameter(Mandatory)][double]$Value)

    if ([math]::Abs($Value) -lt 0.0000005) {
        return '0'
    }

    return $Value.ToString('0.000000', $invariantCulture).TrimEnd('0').TrimEnd('.')
}

function Format-Vector {
    param([Parameter(Mandatory)][double[]]$Value)

    return (($Value | ForEach-Object { Format-Number $_ }) -join ', ')
}

if (-not (Test-Path -LiteralPath $ProfilesPath -PathType Leaf)) {
    throw "Profile file not found: $ProfilesPath"
}

$document = Get-Content -LiteralPath $ProfilesPath -Raw | ConvertFrom-Json
if ($document.schema_version -ne 1) {
    throw "Unsupported profile schema version: $($document.schema_version)"
}

$profiles = @($document.profiles)
if ($profiles.Count -eq 0) {
    throw 'At least one weapon profile is required.'
}

$seenProfileIds = @{}
$seenWeaponSections = @{}
$seenHudSections = @{}
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('; Frosty AK Integration')
$lines.Add('; Generated by tools/generate-profiles.ps1. Edit profiles/weapon-profiles.json instead.')
$lines.Add('; Each weapon owns one MAS transform. Scope-specific offsets remain owned by MAS/PUSSY.')

foreach ($profile in $profiles) {
    $profileId = [string]$profile.id
    if ([string]::IsNullOrWhiteSpace($profileId) -or $seenProfileIds.ContainsKey($profileId)) {
        throw "Profile ids must be non-empty and unique: '$profileId'."
    }
    $seenProfileIds[$profileId] = $true

    $weaponSections = @($profile.weapon_sections)
    $hudSections = @($profile.hud_sections)
    if ($weaponSections.Count -eq 0 -or $hudSections.Count -eq 0) {
        throw "Profile '$profileId' requires weapon_sections and hud_sections."
    }

    $scopeGroup = [string]$profile.scope_group
    if ($scopeGroup -notmatch '^scope_group_[a-z0-9_]+$') {
        throw "Profile '$profileId' has an invalid scope_group."
    }

    $nativePosition = Get-RequiredVector $profile.native_ads 'position' "$profileId.native_ads"
    $nativeRotation = Get-RequiredVector $profile.native_ads 'rotation' "$profileId.native_ads"
    $nativePosition16x9 = Get-OptionalVector $profile.native_ads 'position_16x9' "$profileId.native_ads" $nativePosition
    $nativeRotation16x9 = Get-OptionalVector $profile.native_ads 'rotation_16x9' "$profileId.native_ads" $nativeRotation
    $basePosition = Get-RequiredVector $profile.mas_transform 'base_position' "$profileId.mas_transform"
    $baseRotation = Get-RequiredVector $profile.mas_transform 'base_rotation' "$profileId.mas_transform"
    $basePosition16x9 = Get-OptionalVector $profile.mas_transform 'base_position_16x9' "$profileId.mas_transform" $basePosition
    $baseRotation16x9 = Get-OptionalVector $profile.mas_transform 'base_rotation_16x9' "$profileId.mas_transform" $baseRotation
    $mountPosition = Get-RequiredVector $profile.mas_transform 'mount_position' "$profileId.mas_transform"
    $mountRotation = Get-RequiredVector $profile.mas_transform 'mount_rotation' "$profileId.mas_transform"
    $mountPosition16x9 = Get-OptionalVector $profile.mas_transform 'mount_position_16x9' "$profileId.mas_transform" $mountPosition
    $mountRotation16x9 = Get-OptionalVector $profile.mas_transform 'mount_rotation_16x9' "$profileId.mas_transform" $mountRotation
    $scale = [double]$profile.mas_transform.scale
    if ($scale -le 0 -or [double]::IsNaN($scale) -or [double]::IsInfinity($scale)) {
        throw "Profile '$profileId' requires a finite positive scale."
    }

    $compensatedAimPosition = Subtract-Vector $nativePosition $basePosition
    $compensatedAimRotation = Subtract-Vector $nativeRotation $baseRotation
    $compensatedAimPosition16x9 = Subtract-Vector $nativePosition16x9 $basePosition16x9
    $compensatedAimRotation16x9 = Subtract-Vector $nativeRotation16x9 $baseRotation16x9

    for ($componentIndex = 0; $componentIndex -lt 3; $componentIndex++) {
        $resolvedPosition = $compensatedAimPosition[$componentIndex] + $basePosition[$componentIndex]
        $resolvedRotation = $compensatedAimRotation[$componentIndex] + $baseRotation[$componentIndex]
        $resolvedPosition16x9 = $compensatedAimPosition16x9[$componentIndex] + $basePosition16x9[$componentIndex]
        $resolvedRotation16x9 = $compensatedAimRotation16x9[$componentIndex] + $baseRotation16x9[$componentIndex]
        if ([math]::Abs($resolvedPosition - $nativePosition[$componentIndex]) -gt 0.000000001 -or
            [math]::Abs($resolvedRotation - $nativeRotation[$componentIndex]) -gt 0.000000001 -or
            [math]::Abs($resolvedPosition16x9 - $nativePosition16x9[$componentIndex]) -gt 0.000000001 -or
            [math]::Abs($resolvedRotation16x9 - $nativeRotation16x9[$componentIndex]) -gt 0.000000001) {
            throw "Profile '$profileId' does not preserve its native ADS transform."
        }
    }

    $lines.Add('')
    $lines.Add("; Profile: $profileId")
    foreach ($weaponSectionValue in $weaponSections) {
        $weaponSection = [string]$weaponSectionValue
        if ($weaponSection -notmatch '^wpn_[a-z0-9_]+$' -or $seenWeaponSections.ContainsKey($weaponSection)) {
            throw "Weapon sections must be valid and unique: '$weaponSection'."
        }
        $seenWeaponSections[$weaponSection] = $true

        $lines.Add("![$weaponSection]")
        $lines.Add('modular_attachments                     = true')
        $lines.Add(('modular_scope_group                    = {0}' -f $scopeGroup))
        $lines.Add('scope_status                            = 2')
        $lines.Add('')
    }

    foreach ($hudSectionValue in $hudSections) {
        $hudSection = [string]$hudSectionValue
        if ($hudSection -notmatch '^wpn_[a-z0-9_]+_hud$' -or $seenHudSections.ContainsKey($hudSection)) {
            throw "HUD sections must be valid and unique: '$hudSection'."
        }
        $seenHudSections[$hudSection] = $true

        $lines.Add("![$hudSection]")
        $lines.Add(('aim_hud_offset_pos                     = {0}' -f (Format-Vector $compensatedAimPosition)))
        $lines.Add(('aim_hud_offset_pos_16x9                = {0}' -f (Format-Vector $compensatedAimPosition16x9)))
        $lines.Add(('aim_hud_offset_rot                     = {0}' -f (Format-Vector $compensatedAimRotation)))
        $lines.Add(('aim_hud_offset_rot_16x9                = {0}' -f (Format-Vector $compensatedAimRotation16x9)))
        $lines.Add('')
        $lines.Add(('attach_base_hud_offset_pos             = {0}' -f (Format-Vector $basePosition)))
        $lines.Add(('attach_base_hud_offset_pos_16x9        = {0}' -f (Format-Vector $basePosition16x9)))
        $lines.Add(('attach_base_hud_offset_rot             = {0}' -f (Format-Vector $baseRotation)))
        $lines.Add(('attach_base_hud_offset_rot_16x9        = {0}' -f (Format-Vector $baseRotation16x9)))
        $lines.Add('')
        $lines.Add(('attach_mount_hud_offset_pos            = {0}' -f (Format-Vector $mountPosition)))
        $lines.Add(('attach_mount_hud_offset_pos_16x9       = {0}' -f (Format-Vector $mountPosition16x9)))
        $lines.Add(('attach_mount_hud_offset_rot            = {0}' -f (Format-Vector $mountRotation)))
        $lines.Add(('attach_mount_hud_offset_rot_16x9       = {0}' -f (Format-Vector $mountRotation16x9)))
        $lines.Add(('attach_scale                           = {0}' -f (Format-Number $scale)))
    }
}

$generated = ($lines -join "`n") + "`n"

if ($Check) {
    if (-not (Test-Path -LiteralPath $OutputPath -PathType Leaf)) {
        throw "Generated config not found: $OutputPath"
    }

    $existing = [System.IO.File]::ReadAllText((Resolve-Path -LiteralPath $OutputPath)).Replace("`r`n", "`n")
    if ($existing -cne $generated) {
        throw 'Generated DLTX config is stale. Run tools/generate-profiles.ps1.'
    }

    Write-Host "Profile validation passed: $($profiles.Count) profile(s), $($seenHudSections.Count) HUD section(s)."
    return
}

$outputDirectory = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outputDirectory -PathType Container)) {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
}

[System.IO.File]::WriteAllText($OutputPath, $generated, [System.Text.UTF8Encoding]::new($false))
Write-Host "Generated $OutputPath"
